name: Deploy Backend to Lightsail

on:
  push:
    branches:
      - main   # or your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            echo "-going to folder-"
            cd lifewise-app

            echo "📥 Pull latest code"
            git pull origin main

            echo "📦 Install dependencies"
            npm install

            echo "🔁 Restart server"
            pm2 restart all || pm2 start ecosystem.config.js